#!/usr/bin/env python3
"""Mirror plugins/powerups/skills/ into .agents/skills/ for Devin.

Devin indexes `.agents/skills/<name>/SKILL.md` across connected repos, so the
mirror makes every powerups skill available in Devin sessions. The plugin
directory stays the source of truth; this directory is generated.
"""

import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "plugins" / "powerups" / "skills"
DST = REPO / ".agents" / "skills"
HEADER = (
    "<!-- Generated by scripts/sync-devin-skills.py from "
    "plugins/powerups/skills/{name}/SKILL.md. Do not edit. -->\n"
)
# Claude Code addresses plugin skills as `powerups:<skill>`; Devin uses the
# bare skill name.
REF = re.compile(r"\bpowerups:([a-z0-9-]+)")


def render(path: Path, name: str) -> str:
    text = REF.sub(r"\1", path.read_text())
    if text.startswith("---"):
        end = text.index("\n---", 3) + len("\n---\n")
        return text[:end] + HEADER.format(name=name) + text[end:]
    return HEADER.format(name=name) + text


def main() -> int:
    if not SRC.is_dir():
        print(f"missing source directory: {SRC}", file=sys.stderr)
        return 1
    if DST.exists():
        shutil.rmtree(DST)
    for skill in sorted(p for p in SRC.iterdir() if p.is_dir()):
        src_file = skill / "SKILL.md"
        if not src_file.is_file():
            print(f"skipping {skill.name}: no SKILL.md", file=sys.stderr)
            continue
        out_dir = DST / skill.name
        out_dir.mkdir(parents=True)
        (out_dir / "SKILL.md").write_text(render(src_file, skill.name))
        for extra in sorted(p for p in skill.rglob("*") if p.is_file() and p != src_file):
            target = out_dir / extra.relative_to(skill)
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(extra, target)
        print(f"synced {skill.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
